name = "Zodkoo-based landing page theme"
license = "MIT"
licenselink = "https://github.com/opreaadrian/monolithsplit.com/blob/master/themes/zodkoo-dark/LICENSE.md"
description = ""
tags = ["landing-page", "marketing", "email"]
features = ["form", "email", "responsive"]
min_version = 0.18

[author]
  name = "Adrian Oprea"
  homepage = "https://oprea.rocks"
  email = adrian@oprea.rocks

