# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Landing Page Email Full"
license = "MIT"
licenselink = "https://github.com/opreaadrian/landing-email-full/blob/master/LICENSE.md"
description = ""
tags = ["landing-page", "marketing", "email"]
features = ["form", "email", "responsive"]
min_version = 0.18

[author]
  name = "Adrian Oprea"
  homepage = "https://oprea.rocks"
  email = adrian@oprea.rocks

